before_install:
  - sudo apt-get update --fix-missing
install:
  - pip install six
  - pip install genty
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - python -m unittest discover tests/
