before_install:
  - sudo apt-get update --fix-missing
install:
  - pip install numpy
  - pip install genty
  - pip install pydub
  - pip install "matplotlib<=3.2.1"
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script:
  - python -m unittest discover tests/
